language: python

python:
  - 2.7

sudo: false

install:
  - python setup.py install
  - pip install -r requirements.txt

script:
  - pwd
  - cd datasciencebox/tests
  - py.test -s -vv --cov=datasciencebox
