name: dsb-dev
dependencies:
  - python=2.7
  - click
  - pyyaml
  - paramiko
  # Utils
  - ipython
  - jupyter
  - pandas
  # Tests
  - pylint
  - pytest
  - pip:
    - apache-libcloud
    - salt-ssh
    - watchdog
    # Utils
    - yapf
    - versioneer
    # Tests
    - pytest-cov
    - kazoo
    - hdfs
    - ibis-framework
