name: dsb-dev
dependencies:
  - python=2.7
  - click
  - ipython
  - fabric
  - pytest
  - pyyaml
  - pylint
  - pip:
    - apache-libcloud
    - pytest-cov
    - salt-ssh
    - watchdog
    - yapf
    - versioneer
