name: dsb-dev
dependencies:
  - python=2.7
  - click
  - ipython
  - fabric
  - pyyaml
  - pylint
  - pytest
  - pip:
    - apache-libcloud
    - salt-ssh
    - watchdog
    - yapf
    - versioneer
    - pytest-cov
    - kazoo
    - hdfs
